# Exercise 1

## 데이터 다운로드
---
아래 셀을 실행시켜 데이터를 colab에 불러옵니다.  
셀 실행은 Ctrl + Enter 를 이용해 실행시킬 수 있습니다.

In [2]:
import urllib.request
import zipfile

# wget 대신 urllib 사용하여 다운로드
urllib.request.urlretrieve('https://bit.ly/3gLj0Q6', '3gLj0Q6.zip')

# 압축 해제
with zipfile.ZipFile('3gLj0Q6.zip', 'r') as existing_zip:
    existing_zip.extractall('data')

## 라이브러리 불러오기
---
아래 셀을 실행시켜 pandas 와 DecisionTreeRegressor 를 불러옵니다.

In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

## 데이터 불러오기
---
아래 셀을 실행시켜 csv 파일 데이터를 DataFrame 객체로 불러옵니다.

In [4]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

## 결측치 제거하기
---
결측치를 제거하고, 결측치가 모두 제거됐는지 확인합니다.

In [5]:
test = test.dropna()
train = train.dropna()

print(train.isnull().sum())

id                        0
hour                      0
hour_bef_temperature      0
hour_bef_precipitation    0
hour_bef_windspeed        0
hour_bef_humidity         0
hour_bef_visibility       0
hour_bef_ozone            0
hour_bef_pm10             0
hour_bef_pm2.5            0
count                     0
dtype: int64

1. train 데이터중 <br>
(1) 예측해야할 `count` 피쳐를 drop()함수를 사용하고, axis=1 옵션을 사용해 해당 열을 제외한 데이터들을 `X_train` 이라는 이름의 DataFrame 객체로 만들고 <br>
(2) `count` 피쳐만을 데이터로 갖는 `Y_train` 이라는 이름의 DataFrame 객체로 만드는 코드를 아래에 작성하세요

In [9]:
X_train = train.drop('count', axis=1)
Y_train = train[['count']]

Y_train

      count
0      49.0
1     159.0
2      26.0
3      57.0
4     431.0
...     ...
1454   21.0
1455   20.0
1456   22.0
1457  216.0
1458  170.0

[1328 rows x 1 columns]

2. `model` 변수명으로 모델을 선언하고, fit() 함수를 사용해서, `X_train` 을 input 으로 삼고, `Y_train` 을 output 으로 삼아 모델을 훈련시키는 코드를 아래에 작성하세요

In [11]:
import sklearn
sklearn.set_config(display='text')

model  = DecisionTreeRegressor()
model.fit(X_train, Y_train)

DecisionTreeRegressor()

3. predict() 를 이용해 test data 를 훈련된 모델로 예측한 data 를 생성하고 예측결과 상위 5개를 출력하는 코드를 작성하세요.

In [12]:
pred = model.predict(test)
print(pred[:5])

[117. 143. 121.  49.  93.]

# Exercise 2

## 데이터 다운로드
---
아래 셀을 실행시켜 데이터를 colab 에 불러옵니다.
셀 실행은 Ctrl + Enter 를 이용해 실행시킬 수 있습니다.

In [14]:


import urllib.request
import zipfile

# wget 대신 urllib 사용하여 3i4n1QB.zip 파일로 다운로드
urllib.request.urlretrieve('https://bit.ly/3i4n1QB', '3i4n1QB.zip')

# 압축 해제
with zipfile.ZipFile('3i4n1QB.zip', 'r') as existing_zip:
    existing_zip.extractall('data')

In [15]:
# 라이브러리 불러오기

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

In [17]:
train = pd.read_csv('data/train.csv')

# Scailing
scaler = MinMaxScaler()
scaler.fit(train[['fixed acidity']])
train['Scaled fixed acidity'] = scaler.transform(train[['fixed acidity']])

# Encoding
encoder = OneHotEncoder()
encoder.fit(train[['type']])
onehot = encoder.transform(train[['type']])
onehot = onehot.toarray()
onehot = pd.DataFrame(onehot)
onehot.columns = encoder.get_feature_names_out()
train = pd.concat([train, onehot], axis = 1)
train = train.drop(columns = ['type'])
train.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,Scaled fixed acidity,type_red,type_white
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,0.148760,0.0,1.0
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,0.413223,1.0,0.0
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,0.338843,0.0,1.0
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,0.264463,0.0,1.0
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,0.330579,0.0,1.0

4. sklearn에 model_selection 모듈에서 KFold를 불러와보세요

In [18]:
from sklearn.model_selection import KFold

5. KFold에 n_splits = 5, shuffle = True, random_state = 0이라는 인자를 추가해 "kf"라는 변수에 저장해보세요

In [19]:
kf = KFold(n_splits=5, shuffle =True, random_state=0)

6. 반복문을 통해서 1번부터 5번까지의 데이터에 접근해보세요

In [20]:
for train_index, value_index in kf.split(train):
    print(train_index, value_index)

[   0    1    2 ... 5494 5495 5496] [   4   12   14 ... 5479 5486 5493]
[   0    2    3 ... 5494 5495 5496] [   1    9   22 ... 5472 5478 5490]
[   0    1    4 ... 5493 5494 5496] [   2    3    5 ... 5487 5492 5495]
[   0    1    2 ... 5493 5494 5495] [   8   13   18 ... 5485 5489 5496]
[   1    2    3 ... 5493 5495 5496] [   0    7   21 ... 5488 5491 5494]